name: jyotish_paramarsha
description: A Flutter application for astrological consultation.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  provider: ^6.0.5
  intl: ^0.19.0
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  intl_utils: ^2.8.5
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/logos/
    - assets/images/zodiac/

  fonts:
    - family: Sanskrit
      fonts:
        - asset: assets/fonts/Sanskrit-Regular.ttf
        - asset: assets/fonts/Sanskrit-Bold.ttf
          weight: 700
    - family: Astro
      fonts:
        - asset: assets/fonts/astro-icons.ttf